### ISSUE TITLE
Function Keys not usable: Unknown key name: <F3>

### ISSUE THREAD

**Issue by godspeedyou** [autokey/autokey#442]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: 0.90.4

Used GUI (Gtk, Qt, or both): gtk

If the problem is known to be present in more than one version, please list all of those.

Installed via: PPA

Linux Distribution: Ubuntu 18.04.5

## Summary

Using ` keyboard.send_keys('<alt>+<F3>')` doesn't trigger to open KDE Plasma's Window Menu.

## Steps to Reproduce (if applicable)

- ` keyboard.send_keys('<alt>+<F3>')` or
- ` keyboard.send_keys('<alt>+<f3>')` or
- ` keyboard.send_keys('<alt>+F3')` or
```
keyboard.press_key('<alt>')
keyboard.send_keys('<F3>')
keyboard.release_key('<alt>')
```

## Expected Results

-  open KDE Plasma's Window Menu

## Actual Results

- Nothing.

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```
2020-09-14 09:40:06,867 DEBUG - service - Input stack at end of handle_keypress: [u'!', u'a', u'b']
2020-09-14 09:40:07,125 DEBUG - service - Raw key: ' ', modifiers: [], Key:  
2020-09-14 09:40:07,125 DEBUG - service - Window visible title: u'GroupSpeedDial - Mozilla Firefox', Window class: u'Navigator.Firefox'
2020-09-14 09:40:07,125 DEBUG - service - No phrase/script matched hotkey
2020-09-14 09:40:07,125 DEBUG - service - Script runner executing: Script('arbeitsbrowser')
2020-09-14 09:40:07,126 DEBUG - service - Input stack at end of handle_keypress: []
2020-09-14 09:40:07,126 DEBUG - service - Ignored locking error in handle_keypress
2020-09-14 09:40:07,127 DEBUG - interface - Send special key: ['<backspace>']
2020-09-14 09:40:07,127 DEBUG - iomediator - Send via event interface
2020-09-14 09:40:07,128 DEBUG - interface - Send special key: ['<backspace>']
2020-09-14 09:40:07,129 DEBUG - interface - Send special key: ['<backspace>']
2020-09-14 09:40:07,129 DEBUG - interface - Send special key: ['<backspace>']
2020-09-14 09:40:07,130 DEBUG - interface - Send modified key: modifiers: [u'<alt>'] key: <F3>
2020-09-14 09:40:07,130 ERROR - interface - Unknown key name: <F3>
2020-09-14 09:40:07,130 WARNING - interface - Error sending modified key [u'<alt>'] u'<F3>': ord() expected a character, but string of length 4 found
2020-09-14 09:40:08,504 DEBUG - iomediator - <alt> pressed
2020-09-14 09:40:08,571 DEBUG - service - Raw key: '<tab>', modifiers: ['<alt>'], Key: <tab>
2020-09-14 09:40:08,571 DEBUG - service - Window visible title: u'GroupSpeedDial - Mozilla Firefox', Window class: u'Navigator.Firefox'
2020-09-14 09:40:08,571 DEBUG - service - No phrase/script matched hotkey
2020-09-14 09:40:08,645 DEBUG - iomediator - <alt> released
```

## Notes

-

**Comment by josephj11** [comment]
Until recently, there was no Debian maintainer for the AutoKey package and so they and almost all derivative distributions were stuck with an ancient, buggy version. This is fixed in Debian testing and Ubuntu 20.04 and newer.

Please upgrade to 0.95.10 from this  unsupported version of AutoKey. If your problem persists, let us know.

----

0.90.4 is almost eight years old and unmaintained. You should really upgrade if at all possible.

Unfortunately, Debian had no one assigned to updating their AutoKey package and most Debian-based distributions get AutoKey from them so you still get 0.90.4 when you use their repositories prior to 20.04.

To upgrade:

If you have phrases and scripts, you need to save them:
Make a full backup of $HOME/.config/autokey (including hidden files).
Then uninstall AutoKey.

If you are using Ubuntu 18.04 or a derivative, you can definitely use our pre-built deb files. However, since most of AutoKey is specific Debian release independent, our deb files should work in other Debian-based distros and releases.

All our current deb files are built for Ubuntu 18.04. If you are using a distro which doesn't support deb (apt) packages or installing from the deb packages fails, install using pip. See below.

AutoKey releases are available here:

https://github.com/autokey/autokey/releases/

Select the one you want and then download the common and gtk debs to a directory on your system

Change into that directory (in a terminal) then

To install it on a Debian-based system, use the following:

sudo dpkg --install autokey-common_VERSION_all.deb autokey-gtk_VERSION_all.deb

(substituting the version you downloaded for "VERSION".)

They need to be installed at the same time and dpkg will get it right while apt might not.

If you're using the QT front end, you can download and install that instead of (or in addition to) the GTK version.

Otherwise, you need to install using pip.

Follow the instructions here:
https://github.com/autokey/autokey/wiki/Installing#pip-installation
That will get you up to our current version.

In addition to many bug fixes, this version also adds Xautomation support which allows you to search the screen for an image and move the mouse cursor to it - making it possible to access all sorts of things that keyboard actions alone could not reach.

This version is based on Python3.x, so if you have any scripts which use Python syntax/features which changed from Python2.x, you will have to convert them. Most simple scripts should be unaffected by these changes.

**Comment by josephj11** [comment]
Just looked at this again. Upgrading (which you definitely should do) probably won't help. AutoKey communicates directly with the active application window. This bypasses the desktop environment (DTE), so you can't talk to the DTE directly using our API calls. If you need to do that, you can experiment with other tools such as `xdotool`. When you get something that does what you want, you can invoke it from within an AutoKey script using the `subprocess` module.

**Comment by godspeedyou** [comment]
> Just looked at this again. Upgrading (which you definitely should do) probably won't help. AutoKey communicates directly with the active application window. This bypasses the desktop environment (DTE), so you can't talk to the DTE directly using our API calls. If you need to do that, you can experiment with other tools such as `xdotool`. When you get something that does what you want, you can invoke it from within an AutoKey script using the `subprocess` module.

True, I just updated and F3 unfortunately still doesn't work. I'm going to look into your suggestion.
